### ISSUE TITLE
Which process does one add the handler to?

### ISSUE THREAD

**Issue by finjulhich** [jruere/multiprocessing-logging#1]
I have a main process that launches a pool of processes, each does some loggins. The main process does logging initially, starts the pool and just waits until all processes in the pool have finished.
I redirect stdout and stderr of the main process to a given file, and the pool's processes get the same stdout and stderr. Output gets jumbled

The README says to add the handler.
Do I do that in each process of the pool, or in the main process, or in both?
How do I log to stdout/stderr ?

**Comment by jruere** [comment]
I've not tried it with a pool of processes. I know there's a significant difference between creating a Process and using a Pool.

The `Process` behaves very close to a regular `fork()`, you inherit memory and files.
The `Pool` is different and I have not looked into it. I will eventually but not any time soon. You have the need and, if you have the time, I'd very much appreciate a pull request. :)

In the mean time, I've added a note on the README about this so that others don't waste time re-discovering the problem. Thank you for that! :)

**Comment by jruere** [comment]
finjulhich, could you try calling the new setup function in the initializer of the pool? 

I'll do this myself otherwise when I get some free time.

**Comment by jruere** [comment]
It works. I've updated the README.

**Comment by cjw296** [comment]
Interesting... the initializer is called after the fork, so I'm curious as to how running `install_mp_handler` in the forked process works. How does the received end up getting started in the originating process?

**Comment by jruere** [comment]
That is an excellent point. The function has 6 lines and there isn't much code in total. Please, take a look and if you think there's a bug, please open a new ticket.

**Comment by jruere** [comment]
The recommended steps for Pools in the README make no sense. Thanks for catching this.

I don't know how to fix this without rewriting the library. I will not support this case.

**Comment by cjw296** [comment]
Weirdly, it seems to sort of work. I'm going to have a play with this when I get a chance and hopefully send you a pull request...

**Comment by cjw296** [comment]
...but ignoring Pool, I'm still curious how the receiver gets started in the originating process.

**Comment by jruere** [comment]
That would be awesome. Bear in mind that each process would we writing directly to the file.

**Comment by jruere** [comment]
The problem I'm referring to only applies to Pool. It's clear to me how it works after a normal fork.
