### ISSUE TITLE
Does not work on Windows?

### ISSUE THREAD

**Issue by presidento** [jruere/multiprocessing-logging#37]
Hi, it seems that it does not work on Windows, see the following code. I did what the documentation said:
1. configure logging
2. install_mp_handler
3. profit (start logging, start threads)

Expected result:
```
[WARNING] Main
[WARNING] Thread
```
Actual result:
```
[WARNING] Main
Thread
```

This is because logger is not configured on the new Process when we use "spawn" method - the default and only one available on Windows. 

```python
import multiprocessing
import logging
import sys
import multiprocessing_logging


def thread_test():
    #logging.basicConfig(stream=sys.stdout, format="[%(levelname)s] %(message)s")
    logging.getLogger().warning("Thread")


def main():
    multiprocessing.set_start_method("spawn")

    logging.basicConfig(stream=sys.stdout, format="[%(levelname)s] %(message)s")
    multiprocessing_logging.install_mp_handler()
    logging.getLogger().warning("Main")

    p = multiprocessing.Process(target=thread_test)
    p.start()
    p.join()


if __name__ == "__main__":
    main()
```

The only way to make this working for me was to configure logging on the new process, too.

**Comment by jruere** [comment]
Hello Mr @presidento , indeed it does not work on Windows. The README says: `Only works on POSIX systems and only Linux is supported. It does not work on Windows.`

It appears to work when you configure logging on the other processes since they all independently write to the log but this can have issues if 2 processes happen to write simultaneously.

Sorry I cannot help. :(
