### ISSUE TITLE
Logging is not flushed

### ISSUE THREAD

**Issue by jfuruness** [jruere/multiprocessing-logging#51]
Unlike the normal logging, which flushes after every single call, it would appear that the multiprocessing logging does not get flushed after every call. If this is intentional (due to the multiprocessing constraints/purpose), I think it should be documented. Maybe a function to flush the log buffer would be nice as well. This caused errors in some of my unit tests to check if logging was working.

The script below fails (and after it fails, it does write to the file). If you comment out the multiprocessing handler, it succeeds.
```python
from datetime import datetime
import logging
import os
import time

import multiprocessing_logging

path = f"/tmp/{datetime.now().strftime('%Y_%m_%d_%M_%S.%f')}.log"
if os.path.exists(path):
    os.remove(path)
print(path)

logging.root.handlers = []
logging.basicConfig(level=logging.INFO,
                    format='%(asctime)s-%(levelname)s: %(message)s',
                    handlers=[logging.StreamHandler(),
                              logging.FileHandler(path)])
logging.captureWarnings(True)
multiprocessing_logging.install_mp_handler()

log_str = "test"
logging.info(log_str)
with open(path, "r") as f:
    assert log_str in f.read()
raise Exception
```

**Comment by jfuruness** [comment]
I agree that all handlers do not guarantee flushing. It's just that installing this handler changes the behavior of StreamHandler and FileHandler to not flush, and those do guarantee flushing.

I probably should have realized that (considering this is using multithreading) but I didn't and I'd imagine other newer developers might be surprised by this behavior.

So it might be nice to document that it does not flush after every call. If you don't think it's worth it that's totally understandable, I just figured I'd bring it up.

For a flush function, you could always just flush the current queue rather than flush until the queue is empty. To implement a flush function that would always flush every time something is logged I agree is probably overly complex and might slow things down considerably. So I agree, probably not worth doing.

**Comment by jruere** [comment]
I never relied on this behavior. I wonder how you are using the logging system. I'm afraid it will confuse more than clarify since it's quite a niche problem.

"Flushing the current queue" would mean "if the queue currently has N entries, I'll process N entries and return"?
Could be, it's a peculiar heuristic. It might be useful in extreme cases, perhaps. It will work for your test since you are in the same process.

On the main process, it makes sense. There should be some blocking to prevent multiple threads from consuming the queue.

On the children, I don't know what to do. Probably nothing.

All in all, I don't like this change. It adds complexity for a peculiar use case I don't understand. :)

**Comment by jfuruness** [comment]
Yes that is what I meant by flush the current queue.

I had test cases that made sure logs were being created and written to, and they were failing after I added this library. I figured I'd bring it up (to maybe add to the documentation mainly) because I assumed it might confuse other developers. But if this is the first you're hearing of it maybe it has just confused me lol.

Regardless, thank you for taking the time!
